### General ###

### ENV ###
[env]
TERM = "xterm-256color"
TERM_PROGRAM = "alacritty"

### WINDOW ###
[window]
decorations = "none"
dynamic_padding = false
opacity = 1.0
startup_mode = "Maximized"
title = "Alacritty"
class = { instance = "Alacritty", general = "Alacritty" }
padding = { x = 3, y = 3 }

### SCROLLING ###
[scrolling]
history = 5000

### FONT ###
[font]
normal = { family = "Fira Code", style="Regular"}
bold = { family = "Fira Code", style="Bold" }
italic = { family = "Fira Code", style="Italic" }
bold_italic = { family = "Fira Code", style="Bold Italic"}

size = 11
offset={x = 1, y = 1}


### COLORS ###
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#666666"
blue = "#81a2be"
cyan = "#54ced6"
green = "#9ec400"
magenta = "#b77ee0"
red = "#ff3334"
white = "#282a2e"
yellow = "#f0c674"

[colors.cursor]
cursor = "#ffffff"
text = "#1d1f21"

[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#70c0ba"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#373b41"
yellow = "#e6c547"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

### BELL ###

### SELECTION ###

### CURSOR ###

### TERMINAL ###
[terminal.shell]
program = "/bin/bash"
args = ["-c", "zellij attach job || zellij new-session -s job"]

### MOUSE ###

### HINTS ###

### KEYBOARD ###
[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"


